CREATE TABLE IF NOT EXISTS ROUTINE(
 DAY TEXT,
 FIRST_PERIOD TEXT,
 SECOND_PERIOD TEXT,
 THIRD_PERIOD TEXT,
 BREAK TEXT
 FOURTH_PERIOD TEXT,
 FIFTH_PERIOD TEXT,
 SIXTH_PERIOD TEXT
);

INSERT INTO ROUTINE (DAY, FIRST_PERIOD, SECOND_PERIOD, THIRD_PERIOD, BREAK, FOURTH_PERIOD, FIFTH_PERIOD, SIXTH_PERIOD) VALUES
('SUNDAY', 'B1', 'Science', 'IME','40 MIN', 'E2', 'Math', 'ICT'),
('MONDAY', 'B2', 'Science', 'Math','40 MIN', 'BGS', 'IME', 'E2'),
('TUESDAY', 'Math', 'B1', 'E1','40 MIN', 'Science', 'Ph.Edu', 'IME'),
('WEDNESDAY', 'B2', 'BGS', 'Math','40 MIN', 'ICT', 'E1', 'Game'),
('THURSDAY', 'B2', 'Science', 'B1','40 MIN', 'E2', 'BGS', 'E1');

SELECT * FROM ROUTINE;

SELECT * FROM ROUTINE
WHERE SECOND_CLASS LIKE "S%";

SELECT DAY, SUM(BREAK)
FROM ROUTINE
GROUP BY DAY;

SELECT DAY,
SUM(BREAK) AS "TOTAL BREAK TIME"
FROM ROUTINE
WHERE FIRST_PERIOD = 'B2'
GROUP BY DAY;

SELECT THIRD_PERIOD
HAVING THIRD_PERIOD NOT LIKE 'B%';