CREATE TABLE IF NOT EXISTS CLASS_ROUTINE(
 DAY TEXT,
 FIRST_CLASS TEXT,
 SECOND_CLASS TEXT,
 THIRD_CLASS TEXT,
 FOURTH_CLASS TEXT,
 FIFTH_CLASS TEXT,
 SIXTH_CLASS TEXT
);

INSERT INTO CLASS_ROUTINE (DAY, FIRST_CLASS, SECOND_CLASS, THIRD_CLASS, FOURTH_CLASS, FIFTH_CLASS, SIXTH_CLASS) VALUES
('SUNDAY', 'B1', 'Science', 'IME', 'E2', 'Math', 'ICT'),
('MONDAY', 'B2', 'Science', 'Math', 'BGS', 'IME', 'E2'),
('TUESDAY', 'Math', 'B1', 'E1', 'Science', 'Ph.Edu', 'IME'),
('WEDNESDAY', 'B2', 'BGS', 'Math', 'ICT', 'E1', 'Game'),
('THURSDAY', 'B2', 'Science', 'B1', 'E2', 'BGS', 'E1');

SELECT * FROM CLASS_ROUTINE;

SELECT * FROM CLASS_ROUTINE
WHERE SECOND_CLASS LIKE "S%";